# vim: ft=tmux

# Core Settings
set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:RGB"
set -as terminal-features ",ghostty:RGB:clipboard:mouse"
set -s escape-time 0
set -g focus-events on
set -g mouse on
set -g base-index 1
set -g renumber-windows on
setw -g pane-base-index 1

# Binds
bind C-l send-keys 'C-l'
bind r source-file ~/.config/tmux/tmux.conf

# clipboard & nav
set -g history-limit 50000
set -s set-clipboard on
setw -g mode-keys vi
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel
set -wg mode-style bg=#45475a,fg=#a6e3a1

# Visual (Catppuccin Mocha)
set-option -g status-position top
set -g status-style bg=default
set -g status-justify absolute-centre
set -g pane-active-border-style fg=#89b4fa

set -g status-left "#[fg=#a6e3a1,bold] #S  "
set -g status-left-length 200

set -g window-status-current-format "#[fg=#89b4fa,bg=default] 󰧞 #I #W "
set -g window-status-format "#[fg=#8c8fa1,bg=default]   #I #W "

set -g status-right-length 200
set -g status-interval 2
set -g status-right '#[fg=#dc8a78]#(~/.config/tmux/plugins/tmux-mem-cpu-load/tmux-mem-cpu-load -a 0 -g 0 --interval 2)#[default] '

# Resize panes using Prefix + H, J, K, L
bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5

# Plugins
set -g @plugin 'thewtex/tmux-mem-cpu-load'
set -g @plugin 'christoomey/vim-tmux-navigator'

run '~/.config/tmux/plugins/tpm/tpm'
