[font.normal]
family = "LiterationMono Nerd Font"

# [font.normal]
# family = "JetBrainsMono Nerd Font"

# [font.normal]
# family = "FiraCode Nerd Font"

[terminal.shell]
program = "/bin/bash"

[window]
dynamic_padding = true
opacity = 1

[window.padding]
x = 10
y = 10

[general]
import = ["~/.config/alacritty/catppuccin-mocha.toml"]
